# Site settings
title: itwars.me
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://itwars.me" # the base hostname & protocol for your site
copyright: <p class="copy-left">&copy;</p> 2019 <a href="https://itwars.me/">itwars.me</a>
permalink: /:categories/:title/
permalink: pretty
github: [metadata]

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: light_blue-indigo

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-150918278-1

extlinks:
   attributes: {rel: nofollow, target: _blank}
   rel_exclude: ['host1.com', 'host2.net']